// <auto-generated />
using Letsgo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LetsGo.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Letsgo.Model.LetsTodos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lets_descricao");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lets_genre");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lets_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("lets_preco");

                    b.Property<string>("letsURL")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lets_url");

                    b.HasKey("Id");

                    b.ToTable("viagens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "",
                            Genre = "590",
                            Name = "Brasília",
                            Price = 159.99m,
                            letsURL = "https://agencialetsgo2.netlify.app/imagens/brasilia2.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "",
                            Genre = "3.340",
                            Name = "São Paulo",
                            Price = 119.99m,
                            letsURL = "https://agencialetsgo2.netlify.app/imagens/saopaulo2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "",
                            Genre = "610",
                            Name = "Curitiba",
                            Price = 109.99m,
                            letsURL = "https://agencialetsgo2.netlify.app/imagens/Curitiba3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "",
                            Genre = "590",
                            Name = "Londrina",
                            Price = 99.99m,
                            letsURL = "https://agencialetsgo2.netlify.app/imagens/londrina2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "",
                            Genre = "188",
                            Name = "Manaus",
                            Price = 99.99m,
                            letsURL = "https://agencialetsgo2.netlify.app/imagens/manaus2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "",
                            Genre = "3.430",
                            Name = "Rio de Janeiro",
                            Price = 109.99m,
                            letsURL = "https://agencialetsgo2.netlify.app/imagens/rio-de-janeiro2.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
